name: CI Pipeline for Express App-test

on:
  push:
    branches:
      - '**' # Matches any branch

jobs:
  ci:
    name: Build, Test, and Security Scan
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

    